"""Adding lat lon fields for photo

Revision ID: 36f67cd3ab78
Revises: 0b9fe20f93cf
Create Date: 2024-01-08 01:27:41.501276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36f67cd3ab78"
down_revision: Union[str, None] = "0b9fe20f93cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("photos", sa.Column("longitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("photos", "longitude")
    op.drop_column("photos", "latitude")
    # ### end Alembic commands ###
