"""Fixing extension typo

Revision ID: 4dd8b43fc939
Revises: 6b1031a52ba7
Create Date: 2024-01-08 23:06:10.376130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4dd8b43fc939"
down_revision: Union[str, None] = "6b1031a52ba7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("extension", sa.String(), nullable=True))
    op.drop_column("photos", "extention")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "photos",
        sa.Column("extention", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("photos", "extension")
    # ### end Alembic commands ###
