"""Changing filename field to extension

Revision ID: 6b1031a52ba7
Revises: 96c8b5a0496d
Create Date: 2024-01-08 23:03:55.587487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b1031a52ba7"
down_revision: Union[str, None] = "96c8b5a0496d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("extention", sa.String(), nullable=True))
    op.drop_column("photos", "filename")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "photos",
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("photos", "extention")
    # ### end Alembic commands ###
