"""Added filename field for image

Revision ID: 96c8b5a0496d
Revises: ebda4d1423f9
Create Date: 2024-01-08 22:26:42.454532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96c8b5a0496d"
down_revision: Union[str, None] = "ebda4d1423f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("filename", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("photos", "filename")
    # ### end Alembic commands ###
